# config.py

BASE_TEXTS = {
    "app_title": "🍽️ Tìm Quán Ăn Thông Minh",
    "settings": "🔍 Cài đặt",
    "use_current_location": "📍 Dùng vị trí hiện tại",
    "gps_ok": "GPS OK!",
    "enter_location": "Nhập địa điểm",
    "default_location": "District 1, Ho Chi Minh City",
    "what_to_eat": "Bạn muốn ăn gì?",
    "default_dish": "Bánh mì",
    "dish_help": "Thử nhập: banh my, lẩu, ốc, beef steak...",
    "budget": "Ngân sách",
    "budget_all": "Tất cả",
    "budget_cheap": "Bình dân ($)",
    "budget_medium": "Trung bình ($)",
    "budget_expensive": "Sang trọng ($$)",
    "radius": "Bán kính (m)",
    "search_button": "🚀 Tìm kiếm ngay",
    "searching": "Đang tìm '{}'...",
    "top_results": "Top {} quán gần nhất",
    "you": "Bạn",
    "unnamed": "Quán không tên",
    "diverse": "Đa dạng",
    "navigate": "Đi",
    "navigation": "🚗 Dẫn đường: **{}**",
    "distance": "Quãng đường: {:.2f} km | Thời gian: {} phút",
    "no_results": "Không tìm thấy quán nào phù hợp với từ khóa này.",
    "language": "🌐 Ngôn ngữ / Language",
    "map_tab": "Bản đồ",
    "chatbot_tab": "Trợ lý ảo",
    "budget_cheap": "Bình dân ($)",
    "budget_medium": "Trung bình ($)", 
    "budget_expensive": "Sang trọng ($$)",
    "chatbot_title": "🤖 Trợ lý Ẩm thực AI",
    "chatbot_caption": "Tôi có thể nhìn thấy danh sách quán bạn vừa tìm và tư vấn chi tiết!",
    "clear_chat": "🗑️ Xóa lịch sử chat",
    "suggestion_header": "💡 Gợi ý câu hỏi:",
    "chip_analyze": "Phân tích các quán vừa tìm được?",
    "chip_side_dish": "Món này ăn kèm với gì?",
    "chip_cheapest": "Tìm quán rẻ nhất",
    "chat_placeholder": "Hỏi tôi về các quán vừa tìm thấy...",
    "no_api_key": "⚠️ Vui lòng thiết lập GEMINI_API_KEY trong Streamlit Secrets.",
    "error_msg": "Đã xảy ra lỗi: {}"
}