# config.py

BASE_TEXTS = {
    "app_title": "🍜 Tìm Quán Ăn",
    "settings": "Cài đặt",
    "use_current_location": "📍 Dùng vị trí hiện tại",
    "gps_ok": "GPS OK!",
    "enter_location": "Nhập địa điểm",
    "default_location": "Đại học Khoa học Tự Nhiên",
    "what_to_eat": "Bạn muốn ăn gì?",
    "default_dish": "Bánh mì",
    "dish_help": "Thử nhập: banh my, lẩu, ốc, beef steak...",
    "budget": "Ngân sách",
    "budget_all": "Tất cả",
    "budget_cheap": "Bình dân ($)",
    "budget_medium": "Trung bình ($$)",
    "budget_expensive": "Sang trọng ($$$)",
    "radius": "Bán kính (m)",
    "search_button": "🔍 Tìm kiếm ngay",
    "searching": "Đang tìm '{}'...",
    "top_results": "Danh sách {} quán ăn ngon nhất",
    "you": "Bạn",
    "unnamed": "Quán không tên",
    "diverse": "Đa dạng",
    "navigate": "Đi",
    "navigation": "🚗 Dẫn đường: **{}**",
    "distance": "Quãng đường: {:.2f} km | Thời gian: {} phút",
    "no_results": "Không tìm thấy quán nào phù hợp với từ khóa này.",
    "language": "🌐 Ngôn ngữ",
    "map_tab": "Bản đồ",
    "chatbot_tab": "Trợ lý ảo",
    "chatbot_title": "🤖 Trợ lý Ẩm thực",
    "chatbot_caption": "Tôi có thể nhìn thấy danh sách quán bạn vừa tìm và tư vấn chi tiết!",
    "clear_chat": "🗑️ Xóa lịch sử chat",
    "suggestion_header": "💡 Gợi ý câu hỏi:",
    "chip_analyze": "Phân tích các quán vừa tìm được?",
    "chip_side_dish": "Món này ăn kèm với gì?",
    "chip_cheapest": "Tìm quán rẻ nhất",
    "chat_placeholder": "Hỏi Foodie Guide về ẩm thực",
    "no_api_key": "⚠️ Vui lòng thiết lập GEMINI_API_KEY trong Streamlit Secrets.",
    "error_msg": "Đã xảy ra lỗi: {}",
    "transport_mode": "Phương tiện",
    "mode_driving": "🚗 Xe máy/Ô tô",
    "mode_walking": "🚶 Đi bộ",
    "mode_bicycling": "🚲 Xe đạp",
    "error_no_food_nearby": "Rất tiếc, không tìm thấy quán nào phục vụ món '{}' trong bán kính tìm kiếm.",
    "error_invalid_query": "Tôi không nghĩ '{}' là tên một món ăn. Hãy thử nhập tên món cụ thể (Phở, Pizza...) hoặc loại hình ẩm thực.",
    "try_increasing_radius": "💡 Gợi ý: Hãy thử tăng bán kính tìm kiếm trong phần Cài đặt.",

    # --- [MỚI] DỊCH THUẬT GIAO DIỆN BẢN ĐỒ & CHỈ ĐƯỜNG ---
    "go_to_place_btn": "👉 Đi đến quán số {}",
    "real_route_title": "🗺️ Lộ trình thực tế",
    "actual_dist": "Quãng đường thực tế",
    "driving_dist": "Khoảng cách lái xe",
    "est_time": "Thời gian dự kiến",
    "step_continue_dist": "Đi tiếp {}m",
    
    # Navigation Instructions (Các câu lệnh chỉ đường)
    "nav_left": "Rẽ trái vào {}",
    "nav_right": "Rẽ phải vào {}",
    "nav_slight_left": "Chếch sang trái vào {}",
    "nav_slight_right": "Chếch sang phải vào {}",
    "nav_sharp_left": "Rẽ gắt sang trái vào {}",
    "nav_sharp_right": "Rẽ gắt sang phải vào {}",
    "nav_straight": "Đi thẳng trên {}",
    "nav_uturn": "Quay đầu tại {}",
    "nav_depart": "Xuất phát từ {}",
    "nav_arrive": "Bạn đã đến nơi",
    "nav_roundabout": "Vào vòng xuyến, ra lối thứ {} hướng {}",
    "nav_fork": "Tại ngã rẽ, đi về phía {} ({})",
    "nav_end_of_road": "Đi hết đường, rẽ về hướng {} vào {}",
    "nav_default": "Đi tiếp ({})",
    
    # --- [THÊM MỚI] CÁC TỪ KHÓA CHO TRANG CHỦ & HEADER ---
    "header_question": "Bạn muốn ăn gì hôm nay?",
    "home_feature_nearby": "Tìm quán gần nhất",
    "home_feature_nearby_desc": "Dựa trên vị trí GPS",
    "home_feature_route": "Chỉ đường chi tiết",
    "home_feature_route_desc": "Đi bộ, xe máy, ô tô",
    "home_feature_budget": "Lọc theo ngân sách",
    "home_feature_budget_desc": "Bình dân đến cao cấp",
    "home_feature_ai": "AI tư vấn",
    "home_feature_ai_desc": "Chatbot hỗ trợ 24/7",
    "home_suggestion_label": "🔥 Gợi ý:",
    "home_suggestion_list": "Phở, Bánh mì, Cơm tấm, Pizza, Cà phê, Trà sữa"
}